### ISSUE TITLE
V 3.11 not working

### ISSUE THREAD

**Issue by charlez79** [En3rGy/14100_Hue#34]
![2024_09_27_13_51_29_Window](https://github.com/user-attachments/assets/3c2f2f1e-438c-4d1f-b388-97805ac40ac9)

**Comment by En3rGy** [comment]
As mentioned here before https://knx-user-forum.de/forum/%C3%B6ffentlicher-bereich/knx-eib-forum/1451665-neuer-baustein-hue-group-14100?p=1982228#post1982228
Please add details:

- What did you do?
- What did you expect to happen?
- What happened?
- Did this worked before?
- What changed since then?
- Please add logs, debug outputs, environmental infos, etc. if available

**Comment by En3rGy** [comment]
Additional Error Description:

https://knx-user-forum.de/forum/%C3%B6ffentlicher-bereich/knx-eib-forum/1451665-neuer-baustein-hue-group-14100?p=1991358#post1991358

**Comment by En3rGy** [comment]
Not reproducible / details missing
